"""empty message

Revision ID: 671ccc95d1de
Revises: 
Create Date: 2020-05-10 20:28:53.739861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671ccc95d1de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('pronoun', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('teaching', sa.Boolean(), nullable=False),
    sa.Column('teaching_exp', sa.Text(), nullable=True),
    sa.Column('teaching_help', sa.Boolean(), nullable=True),
    sa.Column('help_calls', sa.Boolean(), nullable=False),
    sa.Column('help_resources', sa.Boolean(), nullable=False),
    sa.Column('sc_maths', sa.Float(), nullable=True),
    sa.Column('other_sub', sa.Text(), nullable=True),
    sa.Column('enrichment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteers')
    # ### end Alembic commands ###
